#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        if systemctl is-active --quiet ir-daemon.service; then
            systemctl stop ir-daemon.service || true
        fi
        if systemctl is-active --quiet ha_gateway_rx.service; then
            systemctl stop ha_gateway_rx.service || true
        fi
        if systemctl is-active --quiet ha_gateway_tx.service; then
            systemctl stop ha_gateway_tx.service || true
        fi
    ;;
esac
exit 0

