#!/bin/sh
set -e

case "$1" in
    remove|upgrade)
        systemctl stop ir-daemon.service || true
        systemctl stop btk-server.service || true
        systemctl disable ir-daemon.service || true
        systemctl disable btk-server.service || true
    ;;
esac
exit 0
